kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: dev
    name: admin-authentication
    namespace: dev
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: admin-authentication
      spec:
        containers:
        - name: admin-authentication
          image: reactivesw/admin-authentication:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_datasource_url
            value: jdbc:postgresql://reactivesw-data/admin_authentication
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
          - name: spring_redis_host
            value: redis
          - name: io_reactivesw_message_topic_signin_name
            value: reactivesw-dev-customer-login
          - name: io_reactivesw_message_topic_signin_version
            value: "1"
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: reactivesw-secret
                key: jwt.secret
- kind: Service
  apiVersion: v1
  metadata:
    name: admin-authentication
    namespace: dev
    labels:
      name: admin-authentication
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30110
    selector:
      name: admin-authentication

